Redo infrastructure and deployment code
BD2KGenomics/dss-azul-indexer pull request #46
Opened 2018-06-12 14:07 UTC by hannes-ucsc

2018-06-12 18:24 UTC, caaespin requested changes
After changing environment variable `make deploy` didn't update the lambda.

2018-06-12 18:24 UTC, caaespin commented on common.mk
> +$(error Please run "source environment" in the data-store repo root directory before running make commands)
data-store. Should be indexer,etc

2018-06-12 18:24 UTC, caaespin commented on common.mk
> +ifneq ($(shell python -c "import sys; print(hasattr(sys, 'real_prefix'))"),True)
Swap with the one above

2018-06-12 18:24 UTC, caaespin commented on common.mk
> +$(error Looks like some or all requirements is missing. Please run 'pip install -r requirements.txt')
Say .dev

2018-06-12 18:24 UTC, caaespin commented on common.mk
> +$(warning Looks like TerraForm is not installed. `make deploy` should still work but `make terraform` will not.)
Make more elaborate

2018-06-12 18:24 UTC, caaespin commented on deployments/dev/environment
> +_set AZUL_DSS_ENDPOINT "https://dss.staging.data.humancellatlas.org/v1"
Make prod as the default.  For all deployments until we are integrated with dcp integration

2018-06-12 20:41 UTC, hannes-ucsc commented on common.mk
> +$(error Please run "source environment" in the data-store repo root directory before running make commands)
Fixed.

2018-06-12 20:43 UTC, hannes-ucsc commented on common.mk
> +ifneq ($(shell python -c "import sys; print(hasattr(sys, 'real_prefix'))"),True)
Fixed.

2018-06-12 20:43 UTC, hannes-ucsc commented on common.mk
> +$(error Looks like some or all requirements is missing. Please run 'pip install -r requirements.txt')
Fixed.

2018-06-12 20:47 UTC, hannes-ucsc commented on common.mk
> +$(warning Looks like TerraForm is not installed. `make deploy` should still work but `make terraform` will not.)
Fixed.

2018-06-12 20:50 UTC, hannes-ucsc commented on deployments/dev/environment
> +_set AZUL_DSS_ENDPOINT "https://dss.staging.data.humancellatlas.org/v1"
All DSS endpoint URLs now point at prod. Will commit that separately.

2018-06-12 23:21 UTC, hannes-ucsc commented
I addressed all issues.

Ready for re-review, @caaespin.

2018-06-12 23:32 UTC, caaespin approved these changes
LGTM

![sealofapproval](https://user-images.githubusercontent.com/15972762/41322519-2b85e62a-6e5e-11e8-9f5f-41fe332cc856.png)

2018-06-13 00:07 UTC, hannes-ucsc commented
I pushed two two last minute fixes.

2018-06-13 00:12 UTC, caaespin approved these changes
LGTM

2018-06-13 01:13 UTC, merged